### ISSUE TITLE
Pricing page - spacing between items and footer

### ISSUE THREAD

**Issue by maxv** [cyph/cyph#54]
Hello,
On my 13" macbook the pricing page items looks like this:
<img width="1057" alt="screen shot 2017-10-27 at 1 12 46 am" src="https://user-images.githubusercontent.com/32175422/32079643-276af034-bab4-11e7-8097-f0b9bb473bce.png">
I think maybe there should be some media queries for this one...?

**Comment by buu700** [comment]
That does look pretty bad. It may be an issue with a WordPress plugin we're using there (cyph.com/blog, /pricing, and a few other pages are exported from a private WordPress instance), or just some misc custom styling we have in there somewhere. Thanks for reporting this Max!

(Closing because the fix won't involve any changes in this repo.)
