### ISSUE TITLE
Break out potassium into a community package?

### ISSUE THREAD

**Issue by cryptoquick** [cyph/cyph#55]
Hi, first of all, amazing work! I'm a TypeScript developer that's very interested in using your code for your novel TypeScript crypto methods under the `potassium` directory for a project I'm working on: [arcjet](https://github.com/arcjet/arcjet) 

However, I'm unsure the license, or intent of maintenance, or expectation of community contributions for this code. My intent certainly isn't to appropriate your code by any means.

Regardless, I might put together a potassium package for you guys, if you don't mind. I'm considering tearing out the NativeCrypto stuff, which isn't that relevant to the Node.js or browser community, and using it and maintaining it for the purpose of hashing passwords and signing data, and various other incredibly useful post-quantum, future-oriented crypto methods.

I might also refactor it in such a way that it uses async/await instead of the older syntax you're using, and maybe add some error handling and tests, where useful.

So, I hope all this is okay, and I encourage you to keep developing in public, since that's awesome and wonderful.

**Comment by buu700** [comment]
Thanks a lot for the interest and the kind words! arcjet sounds really cool (basically IPFS for non-static sites?), so I'd love to do what I can to help. Out of curiosity, how did you end up finding Potassium?

> However, I'm unsure the license, or intent of maintenance, or expectation of community contributions for this code. My intent certainly isn't to appropriate your code by any means.

The Cyph code in general is Ms-RSL ("Microsoft Reference Source License"), which means that it's open source in the sense that you can look at the source code, but otherwise still non-free software (AKA "shared source"). We would theoretically be open to accepting pull requests and taking ownership of contributed code, but forking Cyph or repackaging Cyph code without permission would be a violation of the license.

That being said, exactly what you're talking about is something we've wanted to do at some point whenever we had the time/resources to spare, as there's no real reason for Potassium to stay locked down after we've already open sourced ntru.js, etc.

It'd be cool to see this happen sooner than we would've had a chance to do it, so I'll shoot you an email to follow up on this.

> I'm considering tearing out the NativeCrypto stuff, which isn't that relevant to the Node.js or browser community

Actually, the naming may be a little confusing as-is since just one directory up there's a native-web-crypto-polyfill.ts for NativeScript, but NativeCrypto here is a wrapper for the browser `crypto.subtle` API. If anything, rather than tearing it out, I would want the native crypto support expanded to work with the Node.js `crypto` API.

> I might also refactor it in such a way that it uses async/await instead of the older syntax you're using

What are you referencing? I see that we use `sodium.ready.then(() => sodium.crypto_...)` instead of `async () => { await sodium.ready; return sodium.crypto_...; }` in a few places as a stylistic choice, but otherwise async/await is used exclusively.

> and maybe add some error handling and tests, where useful

Sounds great!

**Comment by cryptoquick** [comment]
That's wonderful news! I've responded to your email. I found out about potassium because I started following the trail of crypto packages you've been helping to maintain, looking for solutions to the sort of trust scenarios I'm trying to come up with during the course of developing a piece of software that allows application developers to run their code on the hardware used by the public community.

Arcjet is a network that seeks to run server applications on commodity, consumer-grade hardware many times cheaper than enterprise cloud datacenter hardware, and instead of paying cloud datacenters to do the work, we'd hope that consumers would step up and form their own network, provided their work gets fairly metered and paid via a trusted blockchain. One possibility is that we even run our servers in front of the modem and offer our own wireless access points, so as to provide a platform where any application built upon the Arcjet network can do its part to sidestep net neutrality issues. Imagine if the backend work of running your website were done nearly locally, while bandwidth between peers can be compressed and optimized. Arcjet currently makes no trust guarantees, it expects the happiest possible path, currently, being experimental software. I'm currently setting the groundwork, however, for coming up with solutions that could be acceptable to application developers. The idea is to create an appliance that ordinary people can install in their own homes, and connect to wirelessly in order to share the Arcjet internet, and in its idle time, serving requests from the wider internet. Arcjet also takes steps to ensure a high replication factor to ensure the uptime of the network and prevent outages as nodes are expected to come and go.

Regardless, it's tough to say what interface pattern we should go with in regards to the differing methods for different platforms. Are you suggesting we add a third, for Node.js? That'd be most beneficial to me, as my app is built on Node.js. The biggest question is, do we expect them to work the same on all platforms? I'd imagine testing would occur by running NativeCrypto APIs in headless Chrome, then comparing results with those from JS and Node.js APIs.
