### ISSUE TITLE
Open source definition

### ISSUE THREAD

**Issue by vmx** [cyph/cyph#59]
I appreciate that you write at https://www.cyph.com/blog/open-source that it is not considered Free Software. Could you please also add that it is not considered open source according to the Open Source Definition (https://opensource.org/docs/osd)?

**Comment by buu700** [comment]
Ah, thanks, that's a great point. I didn't want to confuse anybody since "shared source" is a more obscure term, but also don't want to mislead anyone into thinking Cyph is more open than it is. I'll fix that soon.

**Comment by rysiekpl** [comment]
This has been reported almost 3 months ago. The fix requires minor edits on the website.

At this point this starts to look less like an accidental misunderstanding and more like intentional muddying of the waters and riding on the coat-tails of scores of *actually* Open Source projects to deliberately misguide anyone considering using this closed-source tool.

Please consider re-opening this issue and keep it open until this is fixed.

**Comment by buu700** [comment]
It's only been a few months and I've had higher priorities. That's an odd thing to accuse me of after I already agreed to fix it, but thanks for the reminder. I'll update this when it's fixed.

**Comment by rysiekpl** [comment]
> It's only been a few months and I've had higher priorities. That's an odd thing to accuse me of after I already agreed to fix it, but thanks for the reminder.

Well, it's an odd thing to do for a project that name-drops BlackHat and DEFCON, to misuse that particular term. Combined with closing of the issue and no updates for months, you have to admit it's a bad look...

> I'll update this when it's fixed.

Thank you, I appreciate it!

**Comment by YarmoM** [comment]
I too feel strong about the very liberal use of the term Open Source that does not apply in any sense to this project. It is not uncommon for projects to misrepresent themselves by promising more than they can deliver in hopes to gain notoriety. I do not accuse you of purposely misrepresentating this project, but as a member of the hard working Open Source community, I would appreciate for this issue to be cleared up in the best possible delays. 

Thank you for reopening the issue and I look forward to the changes.

**Comment by buu700** [comment]
Ah, well that's fair. I actually hadn't realized (or had forgotten) that open source (or at least the OSI definition of the term) meant more than "publicly viewable" until this issue was opened.

The blog post in question was made at a time when people were consistently missing what was just a subtle GitHub logo in the header of the site, so we felt it was important to draw attention to our code to the extent that it is open. It's not our intention to mislead anyone about our license or development model.

Again, I'll take care of this soon.

**Comment by eganist** [comment]
For the sake of accountability @buu700 can we pick a deadline? e.g. July 10?

**Comment by buu700** [comment]
Sure. I'll make a point of doing it sooner (planning to do it today), but if it's not done by July 10 then you can all feel free to leave a thumbs down on this comment.

**Comment by buu700** [comment]
All right, this change went out over the weekend.
