### ISSUE TITLE
Remove words "Open Source" on website

### ISSUE THREAD

**Issue by YarmoM** [cyph/cyph#67]
Hey there, back for round 2 :)

On July 2nd [0], you agreed to remove the words "Open Source" from your website (even though the blog post was still named "Open Source"). The reason for this being that Cyph is simply not Open Source and stating so would be deceiving users.

It seems those words have accidentally been put back on the website! I'd like to once again request those words to be taken down, they are still deceiving as Cyph has **nt** changed license and is still very much **not** Open Source.

[0] https://github.com/cyph/cyph/issues/59

@rysiekpl

**Comment by ggarron** [comment]
If your software is not foss do not publicity it like it was

**Comment by hyde-stevenson** [comment]
Hello ! It would be indeed nice to not mention as an opensource software if it's not and have some respect for people of this community that spend a lot of their time, often freely, to provide great opensource alternatives.

**Comment by pcrockett** [comment]
Since most people don't interpret "open" in the very specific way that many developers do, having the term on the website seems at least _understandable_. That said, perhaps a link saying "Public source code" would communicate the idea just as well, while respecting those who have a very specific definition of the word "open."

**Comment by rysiekpl** [comment]
> Since most people don't interpret "open" in the very specific way that many developers do, having the term on the website seems at least _understandable_. That said, perhaps a link saying "Public source code" would communicate the idea just as well, while respecting those who have a very specific definition of the word "open."

The developers had already been informed there is a problem with this use of the term, and have agreed to fix that (#59). The term making a come-back on the home page cannot be considered an accident or unintentional at this point, and as such I can only see it as an intentional attempt at confusing site visitors.

Thing is, terms have meaning, and open-source has a very specific meaning. It is that meaning that is the reason why the developers *want* to use it. If it didn't matter, then why not change it to something different like the suggested `Public source code`, right?

The developers know all of this and yet persist in trying to trick their website visitors into thinking Cyph is actually open-source. This is simply disingenuous.

As such it makes people who work in environments where solutions like Cyph might be beneficial (like myself) very unlikely to even consider using/recommending Cyph. After all, if the developers are knowingly muddying the water around licensing here, what else are they trying to hide?

**Comment by rysiekpl** [comment]
> To clarify, it isn't correct that the term has been added to the website after the fact. As per the original ticket, the only change made was an update to a blog post.

Fair (indeed, [a homepage screenshot from March](https://web.archive.org/web/20200329002155/https://www.cyph.com/) does contain "Open Source").

But also, come on, after the conversation we've had in #59 one would assume *some* level of understanding and good faith, and that would suggest changing the term on the homepage too. After all, the issue is with the use of the term on the site, not with the use of the term in that one specific blogpost.

> "Public source" or something along those lines may make sense here.

That would be totally fine, I'd say.

**Comment by rysiekpl** [comment]
Any news on this?

**Comment by eganist** [comment]
Shareholder here.

I'll nag @buu700 on this today. Worse comes to worst, I'll see if I can PR it. Knowing them, I wouldn't consider this to be intentional; more likely a regression if it was previously fixed.

Sorry about this.

**Comment by buu700** [comment]
There shouldn't be any more incorrect uses of the term on cyph.com anymore, but feel free to open a new ticket or ping me here if you guys find another one.

**Comment by rysiekpl** [comment]
Thank you, this is very appreciated! :+1:
